name = "qwenwork2api"
main = "worker.js"
compatibility_date = "2025-09-01"

[assets]
directory = "./public"

[[kv_namespaces]]
binding = "QWENWORK_KV"
id = "94faab0e49c742daa8857cfc227900a3"

[triggers]
crons = ["0 22 * * *"]
